apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Monitoring-kubernetes-cluster-1
  region: us-east-2

nodeGroups:
  - name: ng-1-1
    instanceType: t2.micro
    desiredCapacity: 5
  - name: ng-2-1
    instanceType:  t2.micro
    desiredCapacity: 5
 